[WIP] Emergency shutdown implementation
opynfinance/GammaProtocol pull request #136
Opened 2020-09-06 20:28 UTC by haythem96

# Task: Feature Name:

## High Level Description

Specific Changes
Function x was added ...

### Code

- [ ] Unit test 100% coverage
- [ ] Does your code follow the naming and code documentation guidelines?

### Documentation

- [ ] Is your code up to date with the spec? 
- [ ] Have you added your tests to the testing doc?

2020-09-08 13:03 UTC, antoncoding approved these changes
Looks good.

2020-09-09 00:41 UTC, aparnakr commented on test/controller.test.ts
> +      )
shouldn't there be a separate function for this?

2020-09-09 00:41 UTC, aparnakr commented on test/controller.test.ts
> +      )
Why comine this and redeemForEmergency?

2020-09-09 00:43 UTC, aparnakr commented on test/controller.test.ts
> +      )
What happens when the otoken has not expired? How will a seller / buyer be able to get their share of $?

2020-09-09 00:44 UTC, aparnakr requested changes
Hmm, how will a seller / buyer be able to get money out of the system if we pause before the short token expires?

2020-09-10 19:27 UTC, aparnakr approved these changes
LGTM

2020-09-10 21:34 UTC, merged