[Certora 13]: Ensure that the margin pool cannot transfer assets to/from itself
opynfinance/GammaProtocol pull request #314
Opened 2020-11-29 16:51 UTC by aparnakr

# [Certora 13]: Ensure that the margin pool cannot transfer assets to/from itself

## High Level Description
Checks that the margin pool cannot transfer assets to / from itself. 

Specific Changes
Added a require condition in transferToPool and transferToUser functions in the marginPool.sol file. 

### Code

- [x] Unit test 100% coverage
- [x] Does your code follow the naming and code documentation guidelines?

### Documentation

- [x] Is your code up to date with the spec? 
- [x] Have you added your tests to the testing doc?

2020-11-29 17:10 UTC, antoncoding approved these changes

2020-11-29 22:10 UTC, haythem96 commented on contracts/MarginPool.sol
> +        require(_user != address(this), "MarginPool: cannot transfer assets from oneself");
This check is not needed as the `safeTransferFrom` will fail if `_user == address(this)`.

2020-11-29 22:11 UTC, haythem96 requested changes
This looks great! I think we just need to remove the check in the `TransferToPool()` as if the `_user == address(pool)`, the `msg.sender` is always the pool address, then the `safeTransferFrom` will fail with `ERC20: transfer amount exceeds allowance`

2020-12-01 09:49 UTC, haythem96 approved these changes

2020-12-01 09:50 UTC, merged