[WIP] Add donate feature
opynfinance/GammaProtocol pull request #399
Opened 2021-05-03 11:39 UTC by haythem96

# Task: Add donate feature

## High Level Description

Specific Changes
Function x was added ...

### Code

- [ ] Unit test 100% coverage
- [ ] Does your code follow the naming and code documentation guidelines?

### Documentation

- [ ] Is your code up to date with the spec? 
- [ ] Have you added your tests to the testing doc?

2021-05-04 12:59 UTC, antoncoding approved these changes

2021-05-04 12:59 UTC, antoncoding commented on contracts/Controller.sol
> +    function donate(address _asset, uint256 _amount) external {
Add comment to this! 😄

2021-05-04 14:27 UTC, CruzMolina commented on contracts/Controller.sol
> +    function donate(address _asset, uint256 _amount) external {
Second this 🙂.

2021-05-04 18:40 UTC, aparnakr approved these changes

2021-05-04 18:41 UTC, aparnakr commented
What is the donate feature for? :D

2021-05-04 18:44 UTC, CruzMolina requested changes
https://github.com/opynfinance/GammaProtocol/pull/399/files#r625758655

Also curious about the idea/story for this.
Was the donate feature meant to be a part of #382 but left out?

2021-05-05 11:12 UTC, antoncoding approved these changes

2021-05-05 13:37 UTC, merged