draft steth pricer
opynfinance/GammaProtocol pull request #439
Opened 2021-07-26 17:56 UTC by chuddster

# Task: Feature Name:

## High Level Description

Specific Changes

* Created a new pricer, STETHPricer
* The Pricer uses the stETH's getPooledEthByShares function to get the price of the stETH token in USD. [reference].
* The logic is similar to CompoundPricer, where it requires the USD price of the underlying to be committed beforehand.
* Unit tests for STETHPricer

### Code

- [ ] Unit test 100% coverage
- [ ] Does your code follow the naming and code documentation guidelines?

### Documentation

- [ ] Is your code up to date with the spec? 
- [ ] Have you added your tests to the testing doc?

2021-08-14 01:37 UTC, aleone requested changes

2021-08-14 01:37 UTC, aleone commented on contracts/interfaces/STETHInterface.sol
> +interface STETHInterface {
We need to use the wstETH interface here, which doesn't include getPooledEthByShares.

2021-08-14 01:37 UTC, aleone commented on contracts/mocks/MockSTETHToken.sol
> +contract MockSTETHToken is ERC20Upgradeable {
This is a mock for stETH, but we need a wstETH token, which has doesn't have getPooledEthByShares.

2021-08-14 01:37 UTC, aleone commented on contracts/pricers/STETHPricer.sol
> +contract STETHPricer is OpynPricerInterface {
I think we should probably call it WSTETHPricer as it is pricing wstETH collateral.

2021-08-14 01:37 UTC, aleone commented on contracts/pricers/STETHPricer.sol
> +        uint256 pricePerShare = stETH.getPooledEthByShares(1 ether);
Here we can use `stEthPerToken()` from the wstETH contract

https://docs.lido.fi/contracts/wsteth

2021-08-14 01:37 UTC, aleone commented on contracts/pricers/STETHPricer.sol
> +        address _stETH,
Throughout, I think should change to wstETH to make it clear we are collateralizing with wstETH.

2021-08-14 01:46 UTC, aleone commented on test/unit-tests/stETHPricer.test.ts
> +  MockSTETHTokenInstance,
Tests need to be updated w new mocks, interface, functions, etc

2021-08-17 14:47 UTC, haythem96 commented
Closing this in favor for #440

2021-08-17 14:47 UTC, closed without merging